FROM python:3.10-slim as os-base

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
RUN apt-get update



FROM os-base as app-base
ENV VENV_PATH=/venv
RUN python3 -m venv $VENV_PATH
RUN $VENV_PATH/bin/pip install -U pip setuptools
RUN $VENV_PATH/bin/pip install poetry
RUN $VENV_PATH/bin/poetry config virtualenvs.create false

ARG APPDIR=/app
ENV DEPLOY_TARGET_SERVER ${DEPLOY_TARGET_SERVER}
ENV DEPLOY_GITHUB_ACCESS_TOKEN  ${DEPLOY_GITHUB_ACCESS_TOKEN}
ENV DEPLOY_GITHUB_REPO  ${DEPLOY_GITHUB_REPO}
ENV IS_PRERELEASE  ${IS_PRERELEASE}
ENV DEPLOY_TEAMCITY  ${DEPLOY_TEAMCITY}
ENV DEPLOY_TEAMCITY_USER  ${DEPLOY_TEAMCITY_USER}
ENV DEPLOY_TEAMCITY_PASSWORD  ${DEPLOY_TEAMCITY_PASSWORD}
ENV DEPLOY_TEAMCITY_BUILD_CONF  ${DEPLOY_TEAMCITY_BUILD_CONF}
ENV TG_BOT_TOKEN  ${TG_BOT_TOKEN}
ENV TG_BOT_CHAT_ID ${TG_BOT_CHAT_ID}
WORKDIR $APPDIR/
COPY tp_deploy_bot ./tp_deploy_bot
COPY pyproject.toml ./pyproject.toml
RUN $VENV_PATH/bin/poetry install --no-dev

FROM app-base as main

CMD $VENV_PATH/bin/poetry run python3 -m tp_deploy_bot
